#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCosmic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UCosmicTest")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudentMobility(StudentMobility instance);
    partial void UpdateStudentMobility(StudentMobility instance);
    partial void DeleteStudentMobility(StudentMobility instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::UCosmic.Properties.Settings.Default.UCosmicTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StudentMobility> StudentMobilities
		{
			get
			{
				return this.GetTable<StudentMobility>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Students.StudentMobility")]
	public partial class StudentMobility : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _studentId;
		
		private string _status;
		
		private int _levelId;
		
		private int _termId;
		
		private int _placeId;
		
		private int _programId;
		
		private System.Nullable<int> _establishmentId;
		
		private System.Nullable<int> _foreignEstablishmentId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstudentIdChanging(int value);
    partial void OnstudentIdChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnlevelIdChanging(int value);
    partial void OnlevelIdChanged();
    partial void OntermIdChanging(int value);
    partial void OntermIdChanged();
    partial void OnplaceIdChanging(int value);
    partial void OnplaceIdChanged();
    partial void OnprogramIdChanging(int value);
    partial void OnprogramIdChanged();
    partial void OnestablishmentIdChanging(System.Nullable<int> value);
    partial void OnestablishmentIdChanged();
    partial void OnforeignEstablishmentIdChanging(System.Nullable<int> value);
    partial void OnforeignEstablishmentIdChanged();
    #endregion
		
		public StudentMobility()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", DbType="Int NOT NULL")]
		public int studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					this.OnstudentIdChanging(value);
					this.SendPropertyChanging();
					this._studentId = value;
					this.SendPropertyChanged("studentId");
					this.OnstudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_levelId", DbType="Int NOT NULL")]
		public int levelId
		{
			get
			{
				return this._levelId;
			}
			set
			{
				if ((this._levelId != value))
				{
					this.OnlevelIdChanging(value);
					this.SendPropertyChanging();
					this._levelId = value;
					this.SendPropertyChanged("levelId");
					this.OnlevelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termId", DbType="Int NOT NULL")]
		public int termId
		{
			get
			{
				return this._termId;
			}
			set
			{
				if ((this._termId != value))
				{
					this.OntermIdChanging(value);
					this.SendPropertyChanging();
					this._termId = value;
					this.SendPropertyChanged("termId");
					this.OntermIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placeId", DbType="Int NOT NULL")]
		public int placeId
		{
			get
			{
				return this._placeId;
			}
			set
			{
				if ((this._placeId != value))
				{
					this.OnplaceIdChanging(value);
					this.SendPropertyChanging();
					this._placeId = value;
					this.SendPropertyChanged("placeId");
					this.OnplaceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programId", DbType="Int NOT NULL")]
		public int programId
		{
			get
			{
				return this._programId;
			}
			set
			{
				if ((this._programId != value))
				{
					this.OnprogramIdChanging(value);
					this.SendPropertyChanging();
					this._programId = value;
					this.SendPropertyChanged("programId");
					this.OnprogramIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_establishmentId", DbType="Int")]
		public System.Nullable<int> establishmentId
		{
			get
			{
				return this._establishmentId;
			}
			set
			{
				if ((this._establishmentId != value))
				{
					this.OnestablishmentIdChanging(value);
					this.SendPropertyChanging();
					this._establishmentId = value;
					this.SendPropertyChanged("establishmentId");
					this.OnestablishmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foreignEstablishmentId", DbType="Int")]
		public System.Nullable<int> foreignEstablishmentId
		{
			get
			{
				return this._foreignEstablishmentId;
			}
			set
			{
				if ((this._foreignEstablishmentId != value))
				{
					this.OnforeignEstablishmentIdChanging(value);
					this.SendPropertyChanging();
					this._foreignEstablishmentId = value;
					this.SendPropertyChanged("foreignEstablishmentId");
					this.OnforeignEstablishmentIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
